pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm ci
  displayName: 'Installing node modules'

- script: npm run lint:ci
  displayName: 'Checking for lint errors'

- script: |
    npm run test:ci
  displayName: 'Run unit tests'

- script: |
    npm run build
  displayName: 'Running webpack build'

- script: |
    npm run cypress:ci
  displayName: 'Running cypress tests'

# Save artifacts to deploy on static server
- task: PublishPipelineArtifact@1
  inputs:
    path: $(Agent.BuildDirectory)/s/build
    artifact: react-static-website-build-artifacts